version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\sergi\go-diff

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - C:\MinGW\bin\mingw32-make install-tools
  - C:\MinGW\bin\mingw32-make install-dependencies
  - cd c:\gopath\src\github.com\sergi\go-diff\
  - C:\MinGW\bin\mingw32-make test
  - C:\MinGW\bin\mingw32-make lint
